### ISSUE TITLE
url rewrite

### ISSUE THREAD

**Issue by chrisdostert** [tutumcloud/haproxy#102]
Sorry for a possibly dumb question but is url rewrite possible? For Example map
*/service1/ => / (remove the service1 path segment from the request)

**Comment by jarlefosen** [comment]
@chrisdostert 
There's something called [reqrep](https://cbonte.github.io/haproxy-dconv/configuration-1.5.html#4.2-reqrep) in HAProxy that does exactly what you ask. But I haven't been able to get it to work.

```
http:
  image: tutum/haproxy
  links:
    - web:web
    - server:server
  ports:
    - 80:80

web:
  build: web
  environment:
    - VIRTUAL_HOST=*/, */*
    - VIRTUAL_HOST_WEIGHT=0

server:
  build: server
  environment:
    - VIRTUAL_HOST=*/socket.io,*/socket.io/*,*/api,*/api/*
    - VIRTUAL_HOST_WEIGHT=1
    - OPTION=reqrep ^([^\ :]*)\ /api/(.*)     \1\ /\2
```

This should proxy requests like this `(http) /api/hello => (server) /hello`.
But it doesn't.

All I get is this which says that `reqreqp` is an unknown option.

```
http_1   | [ALERT] 299/204943 (10) : parsing [/haproxy.cfg:52] : unknown option 'reqrep'.
http_1   | [ALERT] 299/204943 (10) : Error(s) found in configuration file : /haproxy.cfg
http_1   | [ALERT] 299/204943 (10) : Fatal errors found in configuration.
```

I like HAProxy for its simplicity, but at this *corner case* it doesn't work for me.

One solution that should work is to use the following setup
```
nginx -> location /          -> HAProxy -> [web1, web2, ... webN]
      -> location /api/      -> HAProxy -> [srv1, srv2, ... srvN]
      -> location /socket.io -> HAProxy -> [srv1, srv2, ... srvN]
```

In this scenario `/api/` is removed from requests while `/socket.io` is kept when sending to `srv`.
The unmatched cases are sent unaltered to `web`
