### ISSUE TITLE
Tutum Jumpstart different port than 80?

### ISSUE THREAD

**Issue by devpascoe** [tutumcloud/haproxy#105]
Hi, i'm using tutum and looking for a solution that involves basic configuration, is it possible to add a haproxy jumpstart proxy that points to my node app on a different port other than 80?
I can do...
node app set to 3000:dynamic
haproxy if set to 80:80 works fine. But i want haproxy to be 3000:3000 but that doesnt work.

I've also tried playing with setting environment variables BACKEND_PORT, BACKEND_PORTS and FRONTEND_PORT, FRONTENDPORTS with no success.

Am i missing something simple?

**Comment by devpascoe** [comment]
ok, turns out if i group my site and haproxy into a stack it behaves. eg...
```
api-staging:
  image: 'test/api:staging'
  deployment_strategy: high_availability
  ports:
    - '3000'
  sequential_deployment: true
  tags:
    - test
  target_num_containers: 2
lb-api-staging:
  image: 'tutum/haproxy:staging'
  links:
    - api-staging
  ports:
    - '3000:80'
  roles:
    - global
  tags:
    - test
```

**Comment by tifayuki** [comment]
If you use `tutum/haproxy:0.1` you need to set BACKEND_PORT=3000 and FRONTEND_PORT=3000.

If you use `tutum/haproxy:0.2` or `tutum/haproxy:0.3`, you can:
1. use TCP load balancing: set TCP_PORTS=3000 in haproxy container. or
2. use virtual host: set VIRTUAL_HOST=<yourdomain>:3000 in your application containers. 
3. if you don't do anything above, 3000 will be bind to haproxy 80. In this case, what you need to do is to simply publish port 80 to 3000 on haproxy container

**Comment by devpascoe** [comment]
@tifayuki may i see a sample stackfile? I am still seeing unreliable results with my file and here is the latest with your suggestions, correct?

api-staging:
  image: 'test/api:staging'
  deployment_strategy: high_availability
  environment:
    - 'VIRTUAL_HOST=:3000'
  ports:
    - '3000'
  sequential_deployment: true
  tags:
    - test
  target_num_containers: 2
lb-api-staging:
  image: 'tutum/haproxy:staging'
  environment:
    - TCP_PORTS=3000
  links:
    - api-staging
  ports:
    - '3000:80'
  roles:
    - global
  tags:
    - test

**Comment by devpascoe** [comment]
I really want to love this whole tutum thing but i can't seem to reliably get the same site every redeploy. I have 6 sites and i cant seem to map them correctly. Strangely enough i think its not even me because i just tested redeploying then and got someone else's website completely! its in italian!?!?!?

I know its beta and purchased by docker but geez man.

**Comment by devpascoe** [comment]
i'm wondering if its an APEX domain thing, i'm with DNSimple and perhaps their ALIAS hack for root domains to point to cnames had an IP change when i redeployed? www. works.

**Comment by devpascoe** [comment]
bummer, it cant be that. Because a subdomain ended up routing to one of my other sites :(

**Comment by devpascoe** [comment]
ok, i'm realising a few things. haproxy goes wild when redeploying and DNS entries also take a while to settle down. So basically if i redeploy its important to give it a few mins to propagate. This stackfile worked for me having 1 load balancer serving 2 sites, one on 3000 the other on 80

```
api:
  image: 'mystuff/projectnameforapisite:latest'
  environment:
    - 'VIRTUAL_HOST=mywebsite.com:3000'
  sequential_deployment: true
  tags:
    - myapp
  target_num_containers: 1
web:
  image: 'mystuff/projectnameforwebsite:latest'
  environment:
    - 'VIRTUAL_HOST=mywebsite.com:80'
  sequential_deployment: true
  tags:
    - myapp
  target_num_containers: 1
lb:
  image: 'tutum/haproxy:latest'
  links:
    - api
    - web
  ports:
    - '3000:3000'
    - '80:80'
  roles:
    - global
  tags:
    - myapp
```
