### ISSUE TITLE
OPTION=forwardfor does not provide the X-Forwarded-For header in linked service

### ISSUE THREAD

**Issue by PuKoren** [tutumcloud/haproxy#114]
Hello! Thanks for this container, very easy to setup.

But I try to forward client ip to my backend services behind Haproxy, using forwardfor option. It seems that the header is not provided.

Here is my stackfile:
```yml
lb-socket-gateway:
  image: 'tutum/haproxy:latest'
  environment:
    - 'COOKIE=cookie SRV insert indirect nocache maxidle 30m maxlife 8h'
    - MODE=tcp
    - OPTION=forwardfor
  links:
    - service-socket-gateway
  ports:
    - '80:80'
    - '443:443'
    - '1936:1936'
  restart: always
  roles:
    - global
service-socket-gateway:
  image: 'tutum.co/company/service-socket-gateway:latest'
  links:
    - rabbitmq-master
```

Everything is fine and haproxy balance the load, but I can't get the header X-Forward-For. Here is what I get:

```json
{ "host": "lb-socket-gateway.company-env.dialonce.svc.tutum.io",
 "connection": "keep-alive",
 "cache-control": "max-age=0",
 "origin": "http://localhost:3002",
 "user-agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML....",
 "accept": "*/*",
 "referer": "http://localhost:3002",
 "accept-encoding": "gzip, deflate, sdch",
 "accept-language": "fr-FR,fr;q=0.8,en-US;q=0.6,en;q=0.4",
 "cookie": "io=W6diFMdcVaEwg3-uAAAa",
 "x-firephp": "0.4.4",
 "x-firephp-version": "0.4.4",
 "x-wf-max-combined-size": "262144" }
```

Did I do something wrong? Should I configure the forward option from the linked container instead?

Cheers
