### ISSUE TITLE
Can't get VIRTUAL_HOST with scheme to work

### ISSUE THREAD

**Issue by jessesanford** [tutumcloud/haproxy#128]
Keep getting incorrect haproxy configs. I believe there is a parsing error of some sort:

```
admin:
  image: 'tutum.co/foobar/admin:latest'
  environment:
    - 'VIRTUAL_HOST="https://admin.demo.foobar.com"'
demo:
  image: 'tutum.co/foobar/demo:latest'
  environment:
    - 'VIRTUAL_HOST="https://router.api.demo.foobar.com"'
```

```
haproxy-c93a4e68-1 | 2015-12-17T18:57:21.360100591Z frontend port_
haproxy-c93a4e68-1 | 2015-12-17T18:57:21.360107443Z   bind : 
haproxy-c93a4e68-1 | 2015-12-17T18:57:21.360114251Z   acl is_websocket hdr(Upgrade) -i WebSocket
haproxy-c93a4e68-1 | 2015-12-17T18:57:21.360121150Z   acl host_rule_1 hdr(host) -i "https
haproxy-c93a4e68-1 | 2015-12-17T18:57:21.360127942Z   acl host_rule_1_port hdr(host) -i "https:
haproxy-c93a4e68-1 | 2015-12-17T18:57:21.360134836Z   acl path_rule_1 path -i //admin.demo.foobar.com"
haproxy-c93a4e68-1 | 2015-12-17T18:57:21.360141994Z   use_backend SERVICE_ADMIN if path_rule_1 host_rule_1 or path_rule_1 host_rule_1_port
haproxy-c93a4e68-1 | 2015-12-17T18:57:21.360149191Z   acl host_rule_2 hdr(host) -i "https
haproxy-c93a4e68-1 | 2015-12-17T18:57:21.360161215Z   acl host_rule_2_port hdr(host) -i "https:
haproxy-c93a4e68-1 | 2015-12-17T18:57:21.360168136Z   acl path_rule_2 path -i //router.api.demo.foobar.com"
haproxy-c93a4e68-1 | 2015-12-17T18:57:21.360175060Z   use_backend SERVICE_MIDDLEWARE if path_rule_2 host_rule_2 or path_rule_2 host_rule_2_port
haproxy-c93a4e68-1 | 2015-12-17T18:57:21.360181930Z backend SERVICE_ADMIN
haproxy-c93a4e68-1 | 2015-12-17T18:57:21.360188682Z   redirect scheme https code 301 if !{ ssl_fc }
haproxy-c93a4e68-1 | 2015-12-17T18:57:21.360195673Z   server ADMIN_1 10.7.0.4:2000 check
haproxy-c93a4e68-1 | 2015-12-17T18:57:21.360202354Z backend SERVICE_MIDDLEWARE
haproxy-c93a4e68-1 | 2015-12-17T18:57:21.360208994Z   redirect scheme https code 301 if !{ ssl_fc }
haproxy-c93a4e68-1 | 2015-12-17T18:57:21.360215727Z   server MIDDLEWARE_1 10.7.0.1:3000 check
```

**Comment by tifayuki** [comment]
I think it has something to do with the single quote outside the environment variable. Can you remove them and try again?

**Comment by Ubeek** [comment]
I can confirm that this is occurring with myself as well, both with and without single quotes around the vars.

**Comment by fermayo** [comment]
This is an issue with the YML format. It should be like this:

```
admin:
  image: 'tutum.co/foobar/admin:latest'
  environment:
    - "VIRTUAL_HOST=https://admin.demo.foobar.com"
demo:
  image: 'tutum.co/foobar/demo:latest'
  environment:
    - "VIRTUAL_HOST=https://router.api.demo.foobar.com"
```
