### ISSUE TITLE
Socket.IO Node Listeners

### ISSUE THREAD

**Issue by mikepc** [tutumcloud/haproxy#139]
I am finding it really difficult to piece together how to forward socket.io requests with this docker container, I see examples of configuring haproxy.cfg, but that eliminates the dynamic nature of tutum scaling among a number of other different tutum features. 

My nodes run WITH socket.io listening on the app thread.  I've set my VIRTUAL_HOST to wss://my.app.server/socket.io/ and socket.io is not getting picked up by haproxy.

I'm missing key lines from the config I believe, but I'm having a bugger of a time finding a clean method to do this with the docker container. 

I'm out of development schedule, and I really don't want to spin off a separate socket.io server. I'd rather just use a static nginx install that is already working, but I really wanted the load balancing features of haproxy :(.

If anyone has a set of environment variables configured to do what I'm doing I would appreciate it greatly.

**Comment by aPoCoMiLogin** [comment]
Simple don't use `wss://` cause socket.io first will do xhr request, then he will try upgrade it. My `docker-compose.yml` looks like this:

```yaml
socket:
  image: nodejs:latest
  environment:
    - VIRTUAL_HOST=socket.local
proxy:
  image: tutum/haproxy
  ports:
    - "127.0.0.1:80:80"
  links:
    - socket
```

Cheers
