### ISSUE TITLE
Virtual path config for path redirect

### ISSUE THREAD

**Issue by xiphiaz** [tutumcloud/haproxy#154]
I'm trying to work out how to get tutumcloud/haproxy to correctly map virtual hosts/ports to the appropriate container.

The setup is as follows
* two container running nginx, one (`app`) exposes 8080, the other (`api`) exposes 8081

Docker ps output showing this as follows:

```
spira_api_1               /opt/bin/supervisord-start.sh    Up       0.0.0.0:8080->8080/tcp, 9000/tcp                    
spira_app_1               /opt/bin/supervisord-start.sh    Up       0.0.0.0:8081->8081/tcp, 9000/tcp                    
spira_lbhaproxy_1         python /haproxy/main.py          Up       0.0.0.0:1936->1936/tcp, 443/tcp, 0.0.0.0:80->80/tcp
```

What I want to achieve is to have 
* `local.spira.io` go to `app` container
* `local.api.spira.io` go to `api` container
* `local.spira.io/api*` go to `api` container

I set up the rules as follows:

```
api:
  extends:
    file: ./docker/common-services.yml
    service: api
  links:
    - mailcatcher
    - queue
    - cache
    - database
  env_file:
    - ./docker/.local.env
  environment:
    - VIRTUAL_HOST=local.api.spira.io, local.spira.io/api/*
    - NGINX_VHOSTS=/data/docker/config/vhosts/*.conf
    - EXCLUDE_PORTS=9000

app:
  extends:
    file: ./docker/common-services.yml
    service: app
  env_file:
    - ./docker/.local.env
  environment:
    - VIRTUAL_HOST=local.spira.io
    - NGINX_VHOSTS=/data/docker/config/vhosts/*.conf
    - EXCLUDE_PORTS=9000
```

This all seems to be correct in the haproxy logs:

```
lbhaproxy_1 | frontend port_80
lbhaproxy_1 |   bind :80 
lbhaproxy_1 |   acl is_websocket hdr(Upgrade) -i WebSocket
lbhaproxy_1 |   acl host_rule_1 hdr(host) -i local.api.spira.io
lbhaproxy_1 |   acl host_rule_1_port hdr(host) -i local.api.spira.io:80
lbhaproxy_1 |   use_backend SERVICE_SPIRA_API if host_rule_1 or host_rule_1_port
lbhaproxy_1 |   acl host_rule_2 hdr(host) -i local.spira.io
lbhaproxy_1 |   acl host_rule_2_port hdr(host) -i local.spira.io:80
lbhaproxy_1 |   acl path_rule_2 path_reg -i ^/api/.*$
lbhaproxy_1 |   use_backend SERVICE_SPIRA_API if path_rule_2 host_rule_2 or path_rule_2 host_rule_2_port
lbhaproxy_1 |   acl host_rule_3 hdr(host) -i local.spira.io
lbhaproxy_1 |   acl host_rule_3_port hdr(host) -i local.spira.io:80
lbhaproxy_1 |   use_backend SERVICE_APP if host_rule_3 or host_rule_3_port
lbhaproxy_1 |   acl host_rule_4 hdr(host) -i local.mailcatcher.spira.io
lbhaproxy_1 |   acl host_rule_4_port hdr(host) -i local.mailcatcher.spira.io:80
lbhaproxy_1 |   use_backend SERVICE_MAILCATCHER if host_rule_4 or host_rule_4_port
lbhaproxy_1 | backend SERVICE_MAILCATCHER
lbhaproxy_1 |   server MAILCATCHER 172.17.0.6:1080 check
lbhaproxy_1 |   server SPIRA_MAILCATCHER_1 172.17.0.6:1080 check
lbhaproxy_1 | backend SERVICE_SPIRA_API
lbhaproxy_1 |   server SPIRA_API_1 172.17.0.8:8080 check
lbhaproxy_1 |   server API_1 172.17.0.8:8080 check
lbhaproxy_1 | backend SERVICE_APP
lbhaproxy_1 |   server APP_1 172.17.0.4:8081 check
lbhaproxy_1 |   server SPIRA_APP_1 172.17.0.4:8081 check
lbhaproxy_1 | INFO:haproxy:Launching HAProxy
lbhaproxy_1 | INFO:haproxy:HAProxy has been launched(PID: 7)
lbhaproxy_1 | INFO:haproxy:===========END===========

```

However, when I actually use the site, I get a huge number of dropped requests and also the `/api/*` virtual path seems to have no effect. I have tried a number of combinations of `VIRTUAL_HOST_WEIGHT` directives too, with varying effect (sometimes the `app` becomes inaccessible), but none the desired outcome.

Note I am using `docker-compose` for orchestration locally, then once I get that working moving to using tutum cloud.
