### ISSUE TITLE
Setting default for VIRTUAL_HOST_WEIGHT other than zero

### ISSUE THREAD

**Issue by modius** [tutumcloud/haproxy#165]
I have a bunch of different sites on Docker Cloud proxied by HAPROXY.  If a site is not available for whatever reason I would like to show a default maintenance page. I have a container with a simple static HTML page served via **darkhttpd**.

Ideally I'd like to set the default `VIRTUAL_HOST_WEIGHT` for all applications to 1 in the HAPROXY settings.  And then set the specific `VIRTUAL_HOST_WEIGHT` value for the maintenance page to 0.  Is this possible?

If I can't set this default, then i have to remember to set a `VIRTUAL_HOST_WEIGHT` value other than zero in every single web app.

**Comment by tifayuki** [comment]
Haven't test it, but I think you can set a VIRTUAL_HOST_WEIGHT to a negative number, like `-1`

**Comment by modius** [comment]
Thanks @tifayuki -- i got the following Stack running for a maintenance page or rather a catch all for 503's and it appears to work well:

```
dockercloud-maintenance:
  image: 'daemonite/dockercloud-maintenance:latest'
  autoredeploy: true
  environment:
    - 'VIRTUAL_HOST=*.modius.io'
    - VIRTUAL_HOST_WEIGHT=-1
  tags:
    - prod
```
