### ISSUE TITLE
Backend ports with virtual hosts

### ISSUE THREAD

**Issue by spicypixel-** [tutumcloud/haproxy#52]
Seemingly right now VIRTUAL_HOST proxying doesn't have a method of defining a port to proxy to. Given haproxy can proxy to a virtual host with a port using a colon (VIRTUAL_HOST:VIRTUAL_PORT) would it be possible to link to an environmental variable to include the port?

**Comment by tifayuki** [comment]
Yes, It is possible to add port to VIRTUAL_HOST environment variable. I tested it morning.
E.g. in you web application service, you can run with `-e VIRTUAL_HOST: test.org:8000`. Then, in haproxy, you can run:

    docker run -d --link webapp:webapp -e FRONTEND_PORT=8000 -p 8000:8000 tutum/haproxy`

In this case, you can access you web application by `http://test.org:8000`

**Comment by spicypixel-** [comment]
I can't get it to work despite DNS pointing correctly at the tutum host, it resolves the stats page fine and it gives me 503 errors on each of the services with a change to using domain:port for the VIRTUAL_HOST env variables set on my other containers.

**Comment by tifayuki** [comment]
503 means your request cannot be dispatched to any backend.
Check your haproxy logs, and there is something like this:
```
frontend default_frontend
  bind 0.0.0.0:8004
  acl host_WEB-E_ORG:8004 hdr(host) -i web-e.org:8004
  use_backend WEB-E_ORG:8004_cluster if host_WEB-E_ORG:8004
```
In such a case, your request header must be `web-e.org:8004`, any other value will make haproxy return a 503 error.
You can test it by using: `curl -H "HOST:web-e.org:8004" <address>`

Here is an example of how it works:

	docker run -d --name web-e -e HOSTNAME=web-e -e VIRTUAL_HOST="web-e.org:8004" tutum/hello-world
	docker run -d --name lb7 --link web-e:web-e -e FRONTEND_PORT=8004 -p 8004:8004 tifayuki/haproxy-test
	wget --spider --retry-connrefused --no-check-certificate -q -T 5 127.0.0.1:8004 || true
	curl --retry 10 --retry-delay 5 -sSfL -H 'Host:web-e.org:8004' 127.0.0.1:8004 | grep 'My hostname is web-e'

**Comment by spicypixel-** [comment]
Yeah but in your example you need the front and back end port, which makes this of limited value. I need the frontend port to be 80/443 for forwarding into the network, having 8004 open on the front and then linked to a container exposing 8004 has limited value.

**Comment by tifayuki** [comment]
If your application container exposes 8004, you only need to set BACKEND_PORT:

    docker run -d -e BACKEND_PORT=8804 --link webapp:webapp -p 80:80 tutum/haproxy

If you have multi virtual host exposing different ports, say 80, 8080, 8004, you can set `-e BACKEND_PORTS=80,8080, 8084`

**Comment by spicypixel-** [comment]
So all the backend ports need to be set in the haproxy container setup rather than polling the containers when getting their domains? I'll give it a shot. Though how will it know which service is being forwarded to which port? I've got 4 backend containers all running on non standard ports.

**Comment by tifayuki** [comment]
Right now, yes

In one of the previous commits, the BACKEND_PORT was removed. But there could be some problems when the linked services have more than one port exposed. For instance, tutum/wordpress exposes port 80 and 3306. Without the limitation of BACKEND_PORT(S), haproxy will route the traffic to both 80 and 3306. BACKEND_PORT(S) here is more like a filter.

I was thinking to put these settings to the linked service(like VIRTUAL_HOST), so that when you redeploy your application services, haproxy will auto read the configuration from the linked services, configure itself without redeployment.

**Comment by spicypixel-** [comment]
That sounds like an improvement, the flexibility to proxy to defined ports by domain/subdomain would add a lot of flexibility to the setup, otherwise I have to nest haproxy proxying to a set of other haproxy containers (one per service) to bridge 80 to non 80.

**Comment by tifayuki** [comment]
I was thinking to define VIRTUAL_HOST in the format of `http://user:pass@www.tutum.co:80/test` and I will parse the string and extract port 80 as the BACK_END port.

Any suggestion?

**Comment by spicypixel-** [comment]
Any implementation would be good at this point, as long as the port can be specified in addition to the domain to forward to then it's good, having the ability to use HTTP auth and nested folders on the domain is just icing on the cake.

**Comment by ianneub** [comment]
In the case of proxying to backends via the link method could you do something like this on the service that is the target of the proxying:

```
VIRTUAL_HOST=asdf.com
VIRTUAL_PORT=80
```

**Comment by munjalpatel** [comment]
I am in the same exact situation. Spent an entire day yesterday to make it work and found this thread today!

I have an auth-service exposing port 4006 with VIRTUAL_HOST set to 'auth.service.com', and HAProxy listening on port 443. I am able to access the auth-service directly just fine, but when I try to go to https://auth.service.com I keep getting 503. But http://auth.service.com:4006 works fine -- which I don't really want!

What do I need to do in this situation?

**Comment by tifayuki** [comment]
@munjalpatel can you paste your stackfile or the exact way you launched all the services

**Comment by johnstontrav** [comment]
Hey guys,

Im not sure if this is related, but I'm wanting route base on path ie:

VIRTUAL_HOST=blog-containers=example.com/blog, shop-containers=example.com/shop

Is this possible?

**Comment by johnjelinek** [comment]
Here's a stack file:

gitlab:
```
gitlab:
  image: 'sameersbn/gitlab:7.11.4-1'
  deployment_strategy: high_availability
  environment:
    - DB_NAME=mydb
    - DB_USER=myuser
    - GITLAB_BACKUPS=daily
    - GITLAB_HOST=gitlab.johnjelinek.com
    - GITLAB_HTTPS=true
    - GITLAB_PORT=443
    - GITLAB_SSH_PORT=10022
    - VIRTUAL_HOST=gitlab.johnjelinek.com
  links:
    - postgresql
    - 'redis:redisio'
  ports:
    - '443:443'
  volumes_from:
    - gitlab-data
gitlab-data:
  image: 'sytse/gitlab-data:latest'
  command: /bin/true
  volumes:
    - /home/git/data
postgresql:
  image: 'postgres:9.4'
redis:
  image: 'redis:3.0'
```

here's haproxy:
```
prod:
  image: 'tutum/haproxy:latest'
  cpu_shares: 2048
  deployment_strategy: high_availability
  environment:
    - 'BACKEND_PORTS=22,80,443'
  links:
    - 'gitlab.gitlab:gitlab'
  ports:
    - '80:80'
  restart: always
  roles:
    - global
  target_num_containers: 2
```

I have SSL certs installed in the gitlab container. I would like to forward 443 and 22 onto the gitlab container. I'm not sure I'm using `BACKEND_PORTS` right. Also, do I need to modify the ports haproxy needs to accept and what gitlab needs to accept (port 22/80/443 are currently exposed via gitlab container)?
