### ISSUE TITLE
TCP proxy no longer supported?

### ISSUE THREAD

**Issue by motin** [tutumcloud/haproxy#69]
I see you have made lots of additions lately, great! However, is TCP proxy support going away? Virtual hosts are not possible in TCP proxy mode and [if there is no virtual host settings](https://github.com/tutumcloud/haproxy/blob/30c6694a9ae42f8664ed07946165d9e09590785d/haproxy/haproxy.py#L189), the current code defaults to use [port 80](https://github.com/tutumcloud/haproxy/blob/30c6694a9ae42f8664ed07946165d9e09590785d/haproxy/haproxy.py#L255), a port that has no special meaning whatsoever when it comes to tcp mode proxying.

The previous configuration:

```
# HA Proxy for php service scaling
phphaproxy:
  image: tutum/haproxy
  links:
    - phpha
  environment:
    BACKEND_PORT: 9000
    FRONTEND_PORT: 9000
    MODE: tcp

# The highly available php service for interpreting php code without access to /files
phpha:
  image: neam/dna-project-base-debian-php:5.6.7-fpm-0.2.1
  links:
    - mailcatcher
    - redisphpsessionhandler
  volumes:
    - .:/app:rw
  ports:
   - "9000"
  environment:
    DISPLAY_PHP_ERRORS: 'on'
    EXCLUDE_PORTS: 22
```

...yielded a php-fpm load balancer over tcp (ie listening to port 9000 and load-balancing multiple php-fpm backends also serving on port 9000), but the latest changes now results in the following haproxy config:

```
phphaproxy_1             | frontend default_frontend
phphaproxy_1             |   bind :80
phphaproxy_1             |   default_backend default_service
phphaproxy_1             | backend default_service
phphaproxy_1             |   server PROJECTNAME_PHPHA_1 172.17.2.14:9000
phphaproxy_1             |   server PROJECTNAME_PHPHA_2 172.17.2.16:9000
phphaproxy_1             |   server PROJECTNAME_PHPHA_3 172.17.2.18:9000
phphaproxy_1             |   server PHPHA 172.17.2.14:9000
phphaproxy_1             |   server PHPHA_1 172.17.2.14:9000
phphaproxy_1             |   server PHPHA_2 172.17.2.16:9000
phphaproxy_1             |   server PHPHA_3 172.17.2.18:9000
```

This is after adding "EXCLUDE_PORTS: 22" to phpha config. Thus, at least port 22 is not being included in the configuration.

I would instead expect a configuration like the following:
```
phphaproxy_1             | frontend default_frontend
phphaproxy_1             |   bind :9000
phphaproxy_1             |   default_backend default_service
phphaproxy_1             | backend default_service
phphaproxy_1             |   server PROJECTNAME_PHPHA_1 172.17.2.14:9000
phphaproxy_1             |   server PROJECTNAME_PHPHA_2 172.17.2.16:9000
phphaproxy_1             |   server PROJECTNAME_PHPHA_3 172.17.2.18:9000
```
