### ISSUE TITLE
Issue with new environment variables exclude ports

### ISSUE THREAD

**Issue by azmelanar** [tutumcloud/haproxy#75]
Hello,

In my Dockerfile, I expose three ports: 12000, 13000, 16000.

But for load balancing need only one: 13000

So, according to new documentation. I removed BACKEND_PORT and added EXCLUDE_PORTS="12000,16000" (also tested with one, not work)

```
2015-07-22T13:23:28.435145253Z backend default_service
2015-07-22T13:23:28.435145253Z   server SERVICE 10.7.0.69:12000 check
2015-07-22T13:23:28.435145253Z   server SERVICE 10.7.0.69:13000 check
2015-07-22T13:23:28.435145253Z   server SERVICE 10.7.0.69:16000 check
2015-07-22T13:23:28.435145253Z   server SERVICE_1 10.7.0.69:12000 check
2015-07-22T13:23:28.435145253Z   server SERVICE_1 10.7.0.69:13000 check
2015-07-22T13:23:28.435145253Z   server SERVICE_1 10.7.0.69:16000 check
2015-07-22T13:23:28.435145253Z   server SERVICE_2 10.7.0.70:12000 check
2015-07-22T13:23:28.435145253Z   server SERVICE_2 10.7.0.70:13000 check
2015-07-22T13:23:28.435145253Z   server SERVICE_2 10.7.0.70:16000 check
```

But it still display all three ports.

My config:

```
service-111222333:
  image: <service image>
  autorestart: always
  deployment_strategy: high_availability
  target_num_containers: 2
  tags:
    - server
lb:
  image: tutum/haproxy
  autorestart: always
  deployment_strategy: high_availability
  target_num_containers: 2
  environment:
    BALANCE: roundrobin
    MAXCONN: 4096
    MODE: http
    OPTION: redispatch,httplog,dontlognull,forwardfor
    EXCLUDE_PORTS: "12000, 16000"
    SSL_CERT: "-----BEGIN CERTIFICATE-----"
  links:
    - "service-111222333:service"
  ports:
    - "443:443"
  tags:
    - server
```

If you need more information, please let me know.

**Comment by azmelanar** [comment]
Information about tutum/haproxy image:

```
# docker images | grep haproxy
tutum/haproxy                                 latest              bb760a92a401        43 hours ago        231.9 MB
```

**Comment by tifayuki** [comment]
EXCLUDE_PORTS is supposed to set on your application container, not on haproxy

**Comment by azmelanar** [comment]
@tifayuki,

Thanks for answer, but looks like it not enough.

I move EXCLUDE_PORTS to application container:

```
service-111222333:
  image: <service image>
  autorestart: always
  deployment_strategy: high_availability
  target_num_containers: 2
  environment:
    EXCLUDE_PORTS: "12000,16000"
  tags:
    - server
lb:
  image: tutum/haproxy
  autorestart: always
  deployment_strategy: high_availability
  target_num_containers: 2
  environment:
    BALANCE: roundrobin
    MAXCONN: 4096
    MODE: http
    OPTION: redispatch,httplog,dontlognull,forwardfor
    SSL_CERT: "-----BEGIN CERTIFICATE-----"
  links:
    - "service-111222333:service"
  ports:
    - "443:443"
  tags:
    - server
```

And for service its looks ok, but not for container.

```
bitsy-lb-staging-whrlmp858t-1 | 2015-07-22T14:05:33.947302370Z backend default_service
bitsy-lb-staging-whrlmp858t-1 | 2015-07-22T14:05:33.947302370Z   server BITSY 10.7.0.69:13000 check
bitsy-lb-staging-whrlmp858t-1 | 2015-07-22T14:05:33.947302370Z   server BITSY_1 10.7.0.69:12000 check
bitsy-lb-staging-whrlmp858t-1 | 2015-07-22T14:05:33.947302370Z   server BITSY_1 10.7.0.69:13000 check
bitsy-lb-staging-whrlmp858t-1 | 2015-07-22T14:05:33.947302370Z   server BITSY_1 10.7.0.69:16000 check
bitsy-lb-staging-whrlmp858t-1 | 2015-07-22T14:05:33.947302370Z   server BITSY_2 10.7.0.70:12000 check
bitsy-lb-staging-whrlmp858t-1 | 2015-07-22T14:05:33.947302370Z   server BITSY_2 10.7.0.70:13000 check
bitsy-lb-staging-whrlmp858t-1 | 2015-07-22T14:05:33.947302370Z   server BITSY_2 10.7.0.70:16000 check
```

**Comment by tifayuki** [comment]
What are those `bitsy` containers? it doesn't show in your stackfile

**Comment by azmelanar** [comment]
Oops. Its name of linked service, so it should be `service`.

I corrected it in log above.

**Comment by azmelanar** [comment]
Hmmm.. I added virtual host:

```
service-111222333:
  image: <service image>
  restart: always
  deployment_strategy: high_availability
  target_num_containers: 2
  environment:
    VIRTUAL_HOST: "https://example.com"
    EXCLUDE_PORTS: "12000,16000"
    SSL_CERT: "-----BEGIN CERTIFICATE-----"
  tags:
    - server
lb:
  image: tutum/haproxy
  restart: always
  deployment_strategy: high_availability
  target_num_containers: 2
  environment:
    BALANCE: roundrobin
    MAXCONN: 4096
    MODE: http
    OPTION: redispatch,httplog,dontlognull,forwardfor
  links:
    - "service-111222333:service"
  ports:
    - "443:443"
  tags:
    - server
```

and now it looks good:

```
2015-07-22T14:26:26.396389123Z frontend port_443
2015-07-22T14:26:26.396389123Z   bind :443 ssl crt /certs/
2015-07-22T14:26:26.396389123Z   reqadd X-Forwarded-Proto:\ https
2015-07-22T14:26:26.396389123Z   acl host_rule_1 hdr_dom(host) -i example.com
2015-07-22T14:26:26.396389123Z   use_backend SERVICE_SERVICE if host_rule_1
2015-07-22T14:26:26.396389123Z backend SERVICE_SERVICE
2015-07-22T14:26:26.396389123Z   server SERVICE 10.7.0.69:13000 check
```

But I think, it will be good point to add in default backend section only service, not containers. Because for one linked service, no sense to add virtual host (provide more flexibility).
