### ISSUE TITLE
No SSL redirect behaviour in latest version 

### ISSUE THREAD

**Issue by yunspace** [tutumcloud/haproxy#78]
For my personal website and at work, I'm currently using a fork of the HAProxy based on 82115df6c16792b2e49d9dbdc71b9c62c3ec33c3. The fork contains a simple commit which is to add a health check url for Amazon Elastic Load Balancer, nothing else.

I have SSL_CERT setup in my router and my stack looks like this:

```
router:
  image: 'quay.io/trunk/haproxy:1.0'
  deployment_strategy: every_node
  environment:
    - 'BACKEND_PORTS=9000,80'
    - 'RSYSLOG_DESTINATION=my logging vendor'
    - 'SSL_CERT=my key + cert'
  links:
    - hello
    - www
  ports:
    - '80:80'
    - '443:443'
    - '1936:1936'
  privileged: true
  restart: always
  roles:
    - global
```

Everything works. The certificate lock symbol shows up and HTTP requests such as `http://www.yunspace.com` is automatically redirected to HTTPS `https://www.yunspace.com`.  

However if I were to update my stack with the latest from tutum (7979a6de6b741b6a8cee18d6bf4c635af412b8ad):

  image: 'tutum/haproxy:latest'

The HTTP requests no longer redirect to HTTPS. And even if I manually type in the url: `https://www.yunspace.com` the lock symbol doesn't show up and the page doesn't load. I've tried using both `DEFAULT_SSL_CERT` and `SSL_CERT` and it appears `haproxy` is completely ignoring the certificates and only serves HTTP traffic.

I do wish to upgrade to the latest version of haproxy and also merge in our health check url change. However I can't do this until the SSL_CERT is working as before. 

Please confirm what are the new instructions for SSL_CERT setup? Should I be using version `0.1` instead for more stability?

**Comment by tifayuki** [comment]
In order to redirect SSL, you need to set `FORCE_SSL=yes`, as described here: https://github.com/tutumcloud/haproxy#i-want-the-proxy-to-terminate-ssl-connections-and-redirect-http-requests-to-https

Did you try that?

**Comment by yunspace** [comment]
Thanks for the prompt reply. I've added that env var:

```
  image: 'tutum/haproxy:latest'
  deployment_strategy: every_node
  environment:
    - 'BACKEND_PORTS=9000,80'
    - FORCE_SSL=yes
```

Verified the router has restarted with the correct Env Var via the GUI. But still no redirect. Can go to HTTP url only. Going to HTTPS url throws `Failed to load resource: net::ERR_CONNECTION_REFUSED`. No error in the haproxy logs.

However if I simply change to `image: 'tutum/haproxy:0.1` everything works fine. Same env vars and same certificate. By the way my certificate contains private key + intermediate certs + public cert. Not sure if in the latest haproxy the certificate handling logic has changed?
