### ISSUE TITLE
compose links

### ISSUE THREAD

**Issue by amkirwan** [tutumcloud/haproxy#92]
When using docker compose I seem to be getting duplicate server entries in the `haproxy.cfg` file for the links:

docker-compose.yml
```
tutum_1:
  container_name: tutum_1
  image: tutum/hello-world
tutum_2:
  container_name: tutum_2
  image: tutum/hello-world
haproxy:
  container_name: tutum-haproxy
  image: tutum/haproxy:latest
  links:
    - tutum_1
    - tutum_2
```

/haproxy.cfg
```
...
frontend default_frontend
  bind :80
  default_backend default_service
backend default_service
  server TUTUM_1 172.17.0.167:80 check
  server TUTUM_1_1 172.17.0.167:80 check
  server TUTUM_2 172.17.0.166:80 check
  server TUTUM_2_1 172.17.0.166:80
```

Not sure if I have something misconfigured or not but as you can see there should only be 2 servers instead of 4.
